#! /bin/bash
if [ -x /etc/init.d/apache2 ]; then
echo “apache não encontrado, iniciando a instalação….”
sudo apt-get update
sudo apt-get install apache2 -y
else
echo “você ja possui um apache instalado”
fi
sudo mkdir -p /var/www/ifrn/public_html
cd /var/www/ifrn/public_html
sudo git clone https://github.com/matheusmanuel/site-simples-com-html-e-css-.git sudo cp -r site-simples-com-html-e-css-/* . 
sudo rm -rf site-simples-com-html-e-css-/ cd /etc/apache2/site-available/
sudo tee ifrn.conf<<EOF
<VirtualHost *:80>
ServerAdmin admin@ifrn
ServerName ifrn
ServerAlias www.ifrn
DocumentRoot /var/www/ifrn/public_html 
ErroLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF
sudo a2ensite ifrn.conf
sudo echo “127.0.0.1 tfrn” | sudo tee -a /etc/hosts
sudo /etc/init.d/apache2 restart
sudo /etc/init.d/apache2 status
